# Deliverables Schedule  {#Deliverables Schedule}

```         
{#foo}
```

| Identifier | Deliverable | Format |
|:--------------|:----------------|:---------------------------------------|
| L01 | GPS waypoint files | GPS export format. Text file format. |
| L02 | Hydrosurveyor files | Hydrosurveyor export format. Text file format. |
| L03 | Water Quality - Continuous | EXO2 Sonde Probe data and calibration data files. Text file formats. |
| L04 | Water level - HOBO Level Logger | HOBO Level Logger export format. Text file format. |
| L05 | Digital Photographs | TIFF |
| L06 | Data from contracted lab(s) | Formats as received. Text file format. |
| L07 | Chain of custody form | PDF |
| L08 | Scanned field data forms | PDF |
| L09 | Original paper data forms | Paper data forms |
| L10 | Water Quality - Discrete | CSV |
| L11 | Fish length data | NA |
| L12 | Fish abundance data | NA |
| L13 | Ponar | NA |
| L14 | Fish otolith data | NA |
| L15 | Mysids data file | CSV |
| LAG01 | Field data | Human and machine readable text file format. |

```{r, echo = TRUE,warning=FALSE,error=FALSE,include=FALSE}
library(odbc)
library(tidyverse)
Connection = dbConnect(odbc(),Driver = "Sql Server",Server = "inp2300irmadb01\\ntwk", Database = "AKRO")
Sql = "SELECT TOP (1000) [Acronym]
      ,[VitalSign]
      ,[Identifier]
      ,[Deliverable]
      ,[SOP]
      ,[SOPVersion]
      ,[Format]
      ,[Schedule]
      ,[Responsibility]
      ,[ProtocolID]
      ,[DeliverableID]
      ,[Description]
  FROM [AKRO].[dbo].[vwDeliverablesSchedule2]
  where VSID=11 ORDER BY Identifier"
Deliverables = dbGetQuery(Connection,Sql)
knitr::kable(Deliverables %>% select(Identifier,Deliverable,Format))
```
